CREATE DATABASE CuidadoArboles

GO
USE CuidadoArboles
GO

CREATE TABLE Arboles (
ID SMALLINT NOT NULL,
Localizacion VARCHAR (30) NOT NULL,
Fecha_Plantancion DATE NULL,

--PK, FK, UQ
CONSTRAINT PK_Arboles PRIMARY KEY (ID),
)

CREATE TABLE Hojas (
ID SMALLINT NOT NULL,
IsPerenne BIT NOT NULL,
FrecuenciaRiego VARCHAR (25) NULL,
IDArbol SMALLINT NOT NULL,

--PK, FK, UQ
CONSTRAINT PK_Hojas PRIMARY KEY (ID),
CONSTRAINT FK_Hojas_Arboles FOREIGN KEY (IDArbol) REFERENCES Arbol(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE Enfermedades (
Nombre CHAR(25) NOT NULL,
FechaSano DATE NULL,

--PK, FK, UQ
CONSTRAINT PK_Enfermedades PRIMARY KEY (Nombre),
)

CREATE TABLE Acciones (
Nombre CHAR(200) NOT NULL,
NombreEnfermedad CHAR (25) NOT NULL,

--PK, FK, UQ
CONSTRAINT PK_Acciones PRIMARY KEY (Nombre, NombreEnfermedad),
CONSTRAINT FK_Acciones_Enfermedades FOREIGN KEY (NombreEnfermedad) REFERENCES Enfermedades(Nombre) ON DELETE CASCADE ON UPDATE CASCADE,
)

CREATE TABLE Podas (
IDArbol SMALLINT NOT NULL,
Fecha DATE NULL,

--PK, FK, UQ
CONSTRAINT PK_Podas PRIMARY KEY (IDArbol),
CONSTRAINT FK_Podas_Arboles FOREIGN KEY (IDArbol) REFERENCES Arboles(ID) ON DELETE CASCADE ON UPDATE CASCADE,
)

CREATE TABLE Recitales (
Nombre CHAR (40) NOT NULL,

--PK, FK, UQ
CONSTRAINT PK_Recital PRIMARY KEY (Nombre),
)

CREATE TABLE Padrinos (
ID SMALLINT NOT NULL,
Nombre VARCHAR(25) NULL,
Apellidos VARCHAR (45) NOT NULL,
IDArbol SMALLINT NOT NULL,

--PK, FK, UQ
CONSTRAINT PK_Padrinos PRIMARY KEY (ID),
CONSTRAINT FK_Padrinos_Arboles FOREIGN KEY (IDArbol) REFERENCES Arboles(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE Poemas (
Titulo CHAR (40) NOT NULL,
Letra VARCHAR (500) NOT NULL,

--PK, FK, UQ
CONSTRAINT PK_Poemas PRIMARY KEY (Titulo),
)

CREATE TABLE Cantantes (
ID SMALLINT NOT NULL,
Nombre VARCHAR (25) NULL,
Apellidos VARCHAR (45) NOT NULL,
IDRecital SMALLINT NULL,

--PK, FK, UQ
CONSTRAINT PK_Cantantes PRIMARY KEY (ID),
CONSTRAINT FK_Cantantes_Recitales FOREIGN KEY (IDRecital) REFERENCES Recitales(Nombre) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE EnfermedadesArboles (
IDArbol SMALLINT NOT NULL,
NombreEnfermedad CHAR(25) NOT NULL,

--PK, FK, UQ
CONSTRAINT PK_EnfermedadesArboles PRIMARY KEY (IDArbol, NombreEnfermedad),
CONSTRAINT FK_EnfermedadesArboles_Enfermedades FOREIGN KEY (NombreEnfermedad) REFERENCES Enfermedades(Nombre) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_EnfermedadesArboles_Arboles FOREIGN KEY (IDArbol) REFERENCES Arboles(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE RecitalesArboles(
IDArbol SMALLINT NOT NULL,
NombreRecital CHAR (40) NOT NULL,

--PK, FK, UQ
CONSTRAINT PK_EnfermedadesArboles PRIMARY KEY (IDArbol, NombreRecital),
CONSTRAINT FK_RecitalesArboles_Recital FOREIGN KEY (NombreRecital) REFERENCES Recitales(Nombre) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_RecitalesArboles_Arboles FOREIGN KEY (IDArbol) REFERENCES Arboles(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)