CREATE DATABASE Granja
GO
USE Granja
GO

CREATE TABLE Agricultores (
ID INT NOT NULL IDENTITY (1,1),
Nombre VARCHAR (25) NOT NULL,
Apellidos VARCHAR (40) NOT NULL,
Direccion VARCHAR (80) NULL,
Telefono CHAR(9) NULL,
CONSTRAINT PK_Agricultor PRIMARY KEY (ID),
)

CREATE TABLE Tractores (
Matricula CHAR (7) NOT NULL,
Marca VARCHAR (15) NOT NULL,
Modelo VARCHAR (30) NOT NULL,
ID_Agricultor INT NOT NULL,
CONSTRAINT PK_Tractor PRIMARY KEY (Matricula),
CONSTRAINT FK_Tractor_Agricultor FOREIGN KEY (ID_Agricultor) REFERENCES
Agricultores(ID) ON DELETE NO ACTION ON UPDATE CASCADE
)

CREATE TABLE Lotes(
ID INT NOT NULL IDENTITY (1,1),
Peso INT NOT NULL,
Fecha SMALLDATETIME NOT NULL,
Finca_Procedencia CHAR(20) NOT NULL,
Metodo_Ecologico BIT NULL,
Variedad VARCHAR (20) NULL,
ID_Agricultor INT NOT NULL,
CONSTRAINT PK_Lote PRIMARY KEY (ID),
CONSTRAINT FK_Lote_Agricultor FOREIGN KEY (Id_Agricultor) REFERENCES
Agricultores(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_Lote_Finca FOREIGN KEY (Finca_Procedencia) REFERENCES
Fincas(Nombre) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE Fincas (
Nombre CHAR (20) NOT NULL,
Distancia INT NULL,
Municipio VARCHAR (20) NOT NULL,
CONSTRAINT PK_Finca PRIMARY KEY (Nombre),
)

CREATE TABLE Remesas (
ID INT NOT NULL IDENTITY (1,1),
Acidez VARCHAR(20) NULL,
Cantidad INT NOT NULL,
ID_Lote INT NOT NULL,
ID_Distribuidora INT NOT NULL,
CONSTRAINT PK_Remesa PRIMARY KEY (ID),
CONSTRAINT FK_Remesa_Lote FOREIGN KEY (Id_Lote) REFERENCES
Lotes(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_Remesa_Distribuidora FOREIGN KEY (ID_Distribuidora) REFERENCES
Distribuidoras (ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE Distribuidoras(
ID INT NOT NULL IDENTITY (1,1),
Nombre VARCHAR (40) NOT NULL,
Direccion VARCHAR (80) NULL,
Telefono CHAR(9) NOT NULL,
CONSTRAINT PK_Distribuidora PRIMARY KEY (ID),
)