CREATE DATABASE StopDesahucios
GO
USE StopDesahucios
GO

CREATE TABLE Policias (
NumPlaca INT NOT NULL,
Nombre VARCHAR(25) NOT NULL,
Rango VARCHAR (20) NULL,
Alias VARCHAR (20) NULL,
CONSTRAINT PK_Policias PRIMARY KEY (NumPlaca),
)

CREATE TABLE Desahucios (
ID INT NOT NULL IDENTITY (1,1),
Fecha SMALLDATETIME NOT NULL,
Consigna VARCHAR(15) NULL,
ID_Vivienda INT NOT NULL,
CONSTRAINT PK_Desahucios PRIMARY KEY (ID),
CONSTRAINT FK_Desahucio_Vivienda FOREIGN KEY (ID_Vivienda) REFERENCES Viviendas(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE Asociadas (
Num_Socia INT NOT NULL,
Nombre VARCHAR (25) NULL,
Apellidos VARCHAR (45) NOT NULL,
Profesion VARCHAR (20) NULL,
Fecha_Alta SMALLDATETIME NOT NULL,
CONSTRAINT PK_Asociadas PRIMARY KEY (Num_Socia),
)

CREATE TABLE Viviendas (
ID INT NOT NULL IDENTITY (1,1),
Direccion VARCHAR(40) NOT NULL,
Superficie INT NULL,
CONSTRAINT PK_Viviendas PRIMARY KEY (ID)
)

CREATE TABLE Inquilinas (
ID INT NOT NULL IDENTITY (10,1),
Nombre VARCHAR (25) NULL,
Apellidos VARCHAR (45) NOT NULL,
Genero BIT NULL,
Num_Hijas TINYINT NULL,
ID_Vivienda INT NOT NULL,
CONSTRAINT PK_Inquilinas PRIMARY KEY (ID),
CONSTRAINT FK_Inquilinas_Viviendas FOREIGN KEY (ID_Vivienda) REFERENCES Viviendas(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
)

CREATE TABLE Policias_Desahucios (
NumPlaca INT NOT NULL,
ID_Desahucios INT NOT NULL,
CONSTRAINT PK_Policias_Desahucios PRIMARY KEY (NumPlaca, ID_Desahucios),
CONSTRAINT FK_NumPlaca_Policia_Policias_Desahucios FOREIGN KEY (NumPlaca) REFERENCES Policias (NumPlaca) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_ID_Desahucio_Policias_Desahucios FOREIGN KEY (ID_Desahucios) REFERENCES Desahucios (ID) ON DELETE NO ACTION ON UPDATE CASCADE
)

CREATE TABLE Desahucios_Asociadas (
ID_Desahucio INT NOT NULL,
Num_Socia INT NOT NULL,
ISDetenido BIT NULL,
CONSTRAINT PK_Desahucio_Asociada PRIMARY KEY (ID_Desahucio, Num_Socia),
CONSTRAINT FK_Desahucio_Desahucio_Asociadas FOREIGN KEY (ID_Desahucio) REFERENCES Desahucios(ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT FK_Asociadas_Desahucio_Asociadas FOREIGN KEY (Num_Socia) REFERENCES Asociadas(Num_Socia) ON DELETE NO ACTION ON UPDATE NO ACTION,
)