CREATE DATABASE Nidea

GO 
USE Nidea
GO

--DROP DATABASE Nidea
CREATE TABLE Lineas (
ID SMALLINT NOT NULL,
Nombre VARCHAR (30) NOT NULL,

CONSTRAINT PK_Lineas PRIMARY KEY (ID),
)

CREATE TABLE Cosas (
ID SMALLINT NOT NULL,
Nombre VARCHAR (40) NOT NULL,
Precio MONEY NOT NULL,

CONSTRAINT PK_Cosas PRIMARY KEY (ID),
)

CREATE TABLE Sentados (
ID SMALLINT NOT NULL,
Nombre VARCHAR (40) NOT NULL,
Precio MONEY NOT NULL,

CONSTRAINT PK_Sentados PRIMARY KEY (ID),
)

CREATE TABLE Acabados (
Codigo SMALLINT NOT NULL,
Descripcion VARCHAR (150) NULL,

CONSTRAINT PK_Acabados PRIMARY KEY (Codigo),
)

CREATE TABLE Fabricantes (
ID SMALLINT NOT NULL,
Nombre VARCHAR (30) NOT NULL,
Telefono CHAR (9) NULL,
Pais VARCHAR (20) NULL,

CONSTRAINT PK_Fabricantes PRIMARY KEY (ID),
)

CREATE TABLE Piezas (
Codigo SMALLINT NOT NULL,
Denominacion VARCHAR (30) NOT NULL,
Dimension INT NULL,
IDFabricante SMALLINT NOT NULL,

CONSTRAINT PK_Piezas PRIMARY KEY (Codigo),
CONSTRAINT FK_Piezas_Fabricantes FOREIGN KEY (IDFabricante) REFERENCES Fabricantes(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE FabricantesSentados (
IDFabricante SMALLINT NOT NULL,
IDSentado SMALLINT NOT NULL,

CONSTRAINT PK_FabricantesSentados PRIMARY KEY (IDFabricante, IDSentado),
CONSTRAINT FK_FabricantesSentados_Fabricantes FOREIGN KEY (IDFabricante) REFERENCES Fabricantes(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_FabricantesSentados_Sentados FOREIGN KEY (IDSentado) REFERENCES Sentados(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)


CREATE TABLE FabricantesCosas (
IDFabricante SMALLINT NOT NULL,
IDCosa SMALLINT NOT NULL,

CONSTRAINT PK_FabricantesCosa PRIMARY KEY (IDFabricante, IDCosa),
CONSTRAINT FK_FabricantesCosa_Fabricantes FOREIGN KEY (IDFabricante) REFERENCES Fabricantes(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_FabricantesCosas_Cosas FOREIGN KEY (IDCosa) REFERENCES Cosas(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE SentadosAcabados (
IDSentado SMALLINT NOT NULL,
CodigoAcabado SMALLINT NOT NULL,

CONSTRAINT PK_SentadosAcabados PRIMARY KEY (IDSentado, CodigoAcabado),
CONSTRAINT FK_SentadosAcabados_Sentados FOREIGN KEY (IDSentado) REFERENCES Sentados(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_SentadosAcabados_Acabados FOREIGN KEY (CodigoAcabado) REFERENCES Acabados(Codigo) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE CosasAcabado (
IDCosa SMALLINT NOT NULL,
CodigoAcabado SMALLINT NOT NULL,

CONSTRAINT PK_CosasAcabados PRIMARY KEY (IDCosa, CodigoAcabado),
CONSTRAINT FK_CosasAcabados_Cosas FOREIGN KEY (IDCosa) REFERENCES Cosas(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_CosasAcabados_Acabados FOREIGN KEY (CodigoAcabado) REFERENCES Acabados(Codigo) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE CosasPiezas (
IDCosa SMALLINT NOT NULL,
CodigoPieza SMALLINT NOT NULL,

CONSTRAINT PK_CosasPiezas PRIMARY KEY (IDCosa, CodigoPieza),
CONSTRAINT FK_CosasPiezas_Cosas FOREIGN KEY (IDCosa) REFERENCES Cosas(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_CosasPiezas_Piezas FOREIGN KEY (CodigoPieza) REFERENCES Piezas(Codigo) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE PiezasPiezas (
CodigoPieza1 SMALLINT NOT NULL,
CodigoPieza2 SMALLINT NOT NULL,

CONSTRAINT PK_PiezasPiezas PRIMARY KEY (CodigoPieza1, CodigoPieza2),
CONSTRAINT FK_PiezasPiezas_Piezas1 FOREIGN KEY (CodigoPieza1) REFERENCES Piezas(Codigo) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_PiezasPiezas_Piezas2 FOREIGN KEY (CodigoPieza2) REFERENCES Piezas(Codigo) ON DELETE NO ACTION ON UPDATE NO ACTION,
)