CREATE DATABASE MezclasCafes

GO
USE MezclasCafes
GO

--DROP DATABASE MezclasCafes

CREATE TABLE Cafes (
ID SMALLINT NOT NULL IDENTITY (1,1),
Nombre VARCHAR(25) NOT NULL,
LugarOrigen VARCHAR (40) NULL,
Precio MONEY NOT NULL,
CONSTRAINT PK_Cafes PRIMARY KEY (ID),
)

CREATE TABLE Propiedades (
Codigo SMALLINT NOT NULL IDENTITY (1,1),
ISAntioxidante BIT NULL,
ISDigestivo BIT NULL,
ISTonificante BIT NULL,
CONSTRAINT PK_Propiedades PRIMARY KEY (Codigo),
)

CREATE TABLE Clientes (
Nick CHAR (25) NOT NULL,
Nombre VARCHAR (40) NULL,
Direccion VARCHAR (80) NULL,
Contraseña VARCHAR (15) NOT NULL,
CONSTRAINT PK_Clientes PRIMARY KEY (Nick),
)

CREATE TABLE Mezclas (
Codigo SMALLINT NOT NULL IDENTITY (1,1),
NickCliente CHAR (25) NOT NULL,
CONSTRAINT PK_Mezclas PRIMARY KEY (Codigo),
CONSTRAINT FK_Mezclas_Clientes FOREIGN KEY (NickCliente) REFERENCES Clientes(Nick) ON DELETE NO ACTION ON UPDATE CASCADE, 
)


CREATE TABLE CafesPropiedades (
CodigoPropiedades SMALLINT NOT NULL,
IDCafes SMALLINT NOT NULL,
CONSTRAINT PK_CafesPropiedades PRIMARY KEY (CodigoPropiedades, IDCafes),
CONSTRAINT FK_CP_Cafes FOREIGN KEY (IDCafes) REFERENCES Cafes(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_CP_Propiedades FOREIGN KEY (CodigoPropiedades) REFERENCES Propiedades(Codigo) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE CafesMezcla (
IDCafes SMALLINT NOT NULL,
IDMezclas SMALLINT NOT NULL,
Proporcion TINYINT NULL,
CONSTRAINT PK_CafesMezclas PRIMARY KEY (IDCafes, IDMezclas),
CONSTRAINT FK_CafesMezcla_Cafes FOREIGN KEY (IDCafes) REFERENCES Cafes (ID) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_CafesMezcla_Mezclas FOREIGN KEY (IDMezclas) REFERENCES Mezclas (Codigo) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE MezclaCompraCliente (
IDCafes SMALLINT NOT NULL,
IDMezclas SMALLINT NOT NULL,
CONSTRAINT PK_Compra PRIMARY KEY (IDCafes, IDMezclas),
CONSTRAINT FK_Compra_Cafes FOREIGN KEY (IDCafes) REFERENCES Cafes (ID) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_Compra_Mezclas FOREIGN KEY (IDMezclas) REFERENCES Mezclas (Codigo) ON DELETE NO ACTION ON UPDATE CASCADE,
)