CREATE DATABASE ReformasBasilia
GO 
USE ReformasBasilia
GO

CREATE TABLE Proyectos(
ID INT NOT NULL IDENTITY (1,1),
ID_Cliente INT NOT NULL,
CONSTRAINT PK_Proyecto PRIMARY KEY (ID),
CONSTRAINT FK_Proyecto_Cliente FOREIGN KEY (ID_Cliente) REFERENCES Clientes(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE Personas(
ID INT NOT NULL IDENTITY (1,1),
Nombre VARCHAR (25) NULL,
Apellidos VARCHAR (45) NOT NULL,
CONSTRAINT PK_Personas PRIMARY KEY (ID),
)

CREATE TABLE Especialidades (
ID INT NOT NULL IDENTITY (1,1),
CONSTRAINT PK_Especialidad PRIMARY KEY (ID),
)

CREATE TABLE