CREATE DATABASE Urbanizacion

GO 
USE Urbanizacion
GO

CREATE TABLE Propietario (
ID SMALLINT NOT NULL,
Nombre VARCHAR (30) NOT NULL,
Apellidos VARCHAR (80) NOT NULL,
Fecha_Nac SMALLDATETIME NULL,
Sexo BIT NULL,
CONSTRAINT PK_Propietario PRIMARY KEY (ID)
)

CREATE TABLE Vivienda (
ID SMALLINT NOT NULL IDENTITY (1,1),
Direccion VARCHAR (80) NOT NULL,
SHabitable SMALLINT NULL,
SParcela SMALLINT NULL,
IDPropietario SMALLINT NULL,
CONSTRAINT PK_Vivienda PRIMARY KEY (ID),
CONSTRAINT FK_Vivienda_Propietario FOREIGN KEY (IDPropietario) REFERENCES Propietario(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE Inquilino (
ID SMALLINT NOT NULL,
Nombre VARCHAR (30) NOT NULL,
Apellidos VARCHAR (80) NOT NULL,
Fecha_Nac SMALLDATETIME NULL,
Sexo BIT NULL,
IDVivienda SMALLINT NOT NULL,
CONSTRAINT PK_Inquilino PRIMARY KEY (ID),
CONSTRAINT FK_Inquilino_Vivienda FOREIGN KEY (IDVivienda) REFERENCES Vivienda(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE Vehiculo (
Matricula CHAR (7) NOT NULL,
Marca VARCHAR (30) NOT NULL,
Modelo VARCHAR (20) NOT NULL,
AnioFabricacion SMALLINT NULL,
Color VARCHAR (20) NULL,
IDInquilino SMALLINT NOT NULL,
CONSTRAINT PK_Vehiculo PRIMARY KEY (Matricula),
CONSTRAINT FK_Vehiculo_Inquilino FOREIGN KEY (IDInquilino) REFERENCES Inquilino(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE Recibo (
NumeroFactura INT NOT NULL,
Nombre VARCHAR (40) NULL,
Precio MONEY NULL,
IDVivienda SMALLINT NOT NULL,
EsAbonado BIT NOT NULL,
CONSTRAINT PK_Recibo PRIMARY KEY (NumeroFactura),
CONSTRAINT FK_Recibo_Vivienda FOREIGN KEY (IDVivienda) REFERENCES Vivienda(ID) ON UPDATE NO ACTION ON UPDATE CASCADE,
)

