CREATE DATABASE ReformasBasilia
GO 
USE ReformasBasilia
GO

--DROP DATABASE ReformasBasilia

CREATE TABLE Proyectos(
ID INT NOT NULL IDENTITY (1,1),
ID_Cliente INT NOT NULL,
CONSTRAINT PK_Proyecto PRIMARY KEY (ID),
CONSTRAINT FK_Proyecto_Persona FOREIGN KEY (ID_Cliente) REFERENCES Personas(ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
)

CREATE TABLE Personas(
ID INT NOT NULL IDENTITY (1,1),
Nombre VARCHAR (25) NULL,
Apellidos VARCHAR (45) NOT NULL,
CONSTRAINT PK_Personas PRIMARY KEY (ID),
)

CREATE TABLE Especialidades (
ID INT NOT NULL IDENTITY (1,1),
CONSTRAINT PK_Especialidad PRIMARY KEY (ID),
)

CREATE TABLE Participantes (
ID_Proyecto INT NOT NULL,
ID_Externe INT NOT NULL,
CONSTRAINT PK_Participante PRIMARY KEY (ID_Proyecto, Id_Externe),
CONSTRAINT FK_Participante_Proyecto FOREIGN KEY (ID_Proyecto) REFERENCES Proyectos(ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT FK_Participante_Personas FOREIGN KEY (ID_Externe) REFERENCES Personas(ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
)

CREATE TABLE Trabajadores (
ID_Proyecto INT NOT NULL,
ID_Obrere INT NOT NULL,
FechaInicio SMALLDATETIME NOT NULL,
FechaFin SMALLDATETIME NOT NULL,
Hora TIME NOT NULL,
CONSTRAINT PK_Trabajador PRIMARY KEY (ID_Proyecto, ID_Obrere), 
CONSTRAINT FK_Trabajadores_Proyecto FOREIGN KEY (ID_Proyecto) REFERENCES Proyectos(ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT FK_Trabajadores_Personas FOREIGN KEY (ID_Obrere) REFERENCES Personas(ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
)

CREATE TABLE Cualidades (
ID_Especialidad INT NOT NULL,
ID_Obrere INT NOT NULL,
CONSTRAINT PK_Cualidades PRIMARY KEY (ID_Especialidad, ID_Obrere), 
CONSTRAINT FK_Cualidades_Especialidades FOREIGN KEY (ID_Especialidad) REFERENCES Especialidades(ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT FK_Cualidades_Personas FOREIGN KEY (ID_Obrere) REFERENCES Personas(ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
)