CREATE DATABASE ePapaNoel

GO 
USE ePapaNoel
GO

--DROP DATABASE ePapaNoel

CREATE TABLE Proveedores (
ID SMALLINT NOT NULL,
Nombre VARCHAR (30) NOT NULL,
Direccion VARCHAR (80) NULL,
Telefono CHAR (9) NULL,
Valoracion TINYINT NOT NULL,

CONSTRAINT PK_Proveedores PRIMARY KEY (ID),
)

CREATE TABLE Rutas (
ID SMALLINT NOT NULL,
Nombre VARCHAR (40) NOT NULL,

CONSTRAINT PK_Rutas PRIMARY KEY (ID),
)

CREATE TABLE Zonas (
ID SMALLINT NOT NULL,
Nombre VARCHAR (40) NOT NULL,
IDRuta SMALLINT NOT NULL,

CONSTRAINT PK_Zonas PRIMARY KEY (ID),
CONSTRAINT FK_Zonas_Rutas FOREIGN KEY (IDRuta) REFERENCES Rutas (ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE Categorias (
ID SMALLINT NOT NULL,
Nombre VARCHAR (40) NOT NULL,

CONSTRAINT PK_Categorias PRIMARY KEY (ID),
)

CREATE TABLE Personas (
ID INT NOT NULL,
Nombre VARCHAR (30) NOT NULL,
Apellidos VARCHAR (45) NOT NULL,
Fecha_Nac DATE NULL,
IDZona SMALLINT NOT NULL,

CONSTRAINT PK_Personas PRIMARY KEY (ID),
CONSTRAINT FK_Personas_Zonas FOREIGN KEY (IDZona) REFERENCES Zonas (ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE Acciones (
ID INT NOT NULL,
Descripcion VARCHAR (200) NOT NULL,
Fecha DATE NULL,
Lugar VARCHAR (40) NULL,
Motivo VARCHAR (50) NOT NULL,
IDPersona INT NOT NULL,

CONSTRAINT PK_Acciones PRIMARY KEY (ID),
CONSTRAINT FK_Acciones_Personas FOREIGN KEY (IDPersona) REFERENCES Personas(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE Buenas (
IDAccion INT NOT NULL,
IsRecompensa BIT NOT NULL,
IsPeriodico BIT NOT NULL,

CONSTRAINT PK_Buenas PRIMARY KEY (IDAccion),
CONSTRAINT FK_Buenas_Acciones FOREIGN KEY (IDAccion) REFERENCES Acciones (ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE Malas (
IDAccion INT NOT NULL,
IsLey BIT NOT NULL,
Coste MONEY NOT NULL,
PersonasAfectadas SMALLINT NULL,

CONSTRAINT PK_Malas PRIMARY KEY (IDAccion),
CONSTRAINT FK_Malas_Acciones FOREIGN KEY (IDAccion) REFERENCES Acciones (ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE Productos (
ID INT NOT NULL,
Nombre VARCHAR (30) NOT NULL,
Descripcion VARCHAR (100) NULL,
IDCategoria SMALLINT NOT NULL,

CONSTRAINT PK_Productos PRIMARY KEY (ID),
CONSTRAINT FK_Productos_Categorias FOREIGN KEY (IDCategoria) REFERENCES Categorias (ID) ON DELETE NO ACTION
)

CREATE TABLE Pedidos (
Numero INT NOT NULL,
Cantidad SMALLINT NOT NULL,
IDProveedor SMALLINT NOT NULL,

CONSTRAINT PK_Pedidos PRIMARY KEY (Numero),
CONSTRAINT FK_Pedidos_Proveedores FOREIGN KEY (IDProveedor) REFERENCES Proveedores (ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE Familiares (
IDPersona INT NOT NULL,
IDFamiliar INT NOT NULL,

CONSTRAINT PK_Familiares PRIMARY KEY (IDPersona, IDFamiliar),
CONSTRAINT PK_Familiares_Personas FOREIGN KEY (IDPersona) REFERENCES Personas (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT PK_Familiares_Familiares FOREIGN KEY (IDFamiliar) REFERENCES Personas (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
)

CREATE TABLE Peticiones (
ID INT NOT NULL,
Nombre VARCHAR (30) NOT NULL,
IsAceptada BIT NOT NULL,
IDPersona INT NOT NULL,
NumeroPedido INT NOT NULL,
IDRuta SMALLINT NOT NULL,

CONSTRAINT PK_Peticiones PRIMARY KEY (ID),
CONSTRAINT FK_Peticiones_Personas FOREIGN KEY (IDPersona) REFERENCES Personas (ID) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_Peticiones_Pedidos FOREIGN KEY (NumeroPedido) REFERENCES Pedidos (Numero) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_Peticiones_Rutas FOREIGN KEY (IDRuta) REFERENCES Rutas (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
)

CREATE TABLE PeticionesProductos (
IDPeticion INT NOT NULL,
IDProducto INT NOT NULL,

CONSTRAINT PK_PeticionesProductos PRIMARY KEY (IDPeticion, IDProducto),
CONSTRAINT FK_PeticionesProductos_Peticiones FOREIGN KEY (IDPeticion) REFERENCES Peticiones (ID) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_PeticionesProductos_Productos FOREIGN KEY (IDProducto) REFERENCES Productos (ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE ProductosAlternativos (
ID INT NOT NULL,
Nombre VARCHAR (40) NULL,
Precio MONEY NOT NULL,
IDProducto INT NOT NULL,

CONSTRAINT PK_ProductosAlternativos PRIMARY KEY (ID),
CONSTRAINT FK_ProductosAlternativos_Productos FOREIGN KEY (IDProducto) REFERENCES Productos (ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE ProductosPedidos (
IDProducto INT NOT NULL,
NumeroPedido INT NOT NULL,

CONSTRAINT PK_ProductosPedidos PRIMARY KEY (NumeroPedido, IDProducto),
CONSTRAINT FK_ProductosPedidos_Pedidos FOREIGN KEY (NumeroPedido) REFERENCES Pedidos (Numero) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_ProductosPedidos_Productos FOREIGN KEY (IDProducto) REFERENCES Productos (ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)