CREATE DATABASE Hospital

GO 
USE Hospital
GO

CREATE TABLE Medicos(
NColegiado INT NOT NULL CONSTRAINT PK_Medico PRIMARY KEY,
Nombre VARCHAR(25) NULL,
Apellidos VARCHAR (50) NOT NULL,
)

CREATE TABLE Usuarios (
NSSSS INT NOT NULL CONSTRAINT PK_Usuario PRIMARY KEY,
Nombre VARCHAR(25) NULL,
Apellidos VARCHAR (50) NOT NULL,
NMedico INT NOT NULL,
CONSTRAINT FK_UsuarioMedico FOREIGN KEY (NMedico) REFERENCES Medicos(NColegiado) ON DELETE NO ACTION ON UPDATE CASCADE,
)