CREATE DATABASE Agencia
GO
USE Agencia
GO

CREATE TABLE Pasajeros (
ID INT NOT NULL IDENTITY (1,1),
Nombre VARCHAR (25) NULL,
Apellidos VARCHAR (45) NOT NULL,
CONSTRAINT PK_Pasajeros PRIMARY KEY (ID),
)

CREATE TABLE Vuelos (
Codigo INT NOT NULL,
CONSTRAINT PK_Vuelo PRIMARY KEY (Codigo),
)

CREATE TABLE Asientos (
Fila INT NOT NULL,
Letra CHAR(1) NOT NULL,
CONSTRAINT PK_Asiento_Fila_Letra PRIMARY KEY (Fila, Letra),
)

CREATE TABLE Viajes(
ID_Pasajero INT NOT NULL,
Codigo_Vuelo INT NOT NULL,
FilaViaje INT NOT NULL,
Letra CHAR(1) NOT NULL,
CONSTRAINT PK_Viajes PRIMARY KEY (ID_Pasajero, Codigo_Vuelo, FilaViaje, Letra),
CONSTRAINT FK_Viaje_Pasajero FOREIGN KEY (ID_Pasajero) REFERENCES Pasajeros(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_Viaje_Vuelo FOREIGN KEY (Codigo_Vuelo) REFERENCES Vuelos(Codigo) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_Viaje_Asiento_Fila_Letra FOREIGN KEY (FilaViaje, Letra) REFERENCES Asientos(Fila, Letra) ON DELETE NO ACTION ON UPDATE CASCADE,
)