CREATE DATABASE Fracking

GO
USE Fracking
GO

--DROP DATABASE Fracking

CREATE TABLE Parcelas (
ID SMALLINT NOT NULL,
Extension SMALLINT NULL,

CONSTRAINT PK_Parcelas PRIMARY KEY (ID),
)

CREATE TABLE Limites (
ID SMALLINT NOT NULL,
Latitud SMALLINT NOT NULL,
Longitud SMALLINT NOT NULL,

CONSTRAINT PK_Limites PRIMARY KEY (ID),
)

CREATE TABLE Propietarios (
ID SMALLINT NOT NULL,
Nombre VARCHAR (25) NOT NULL,
Apellidos VARCHAR (45) NOT NULL,
Numero TINYINT NULL,

CONSTRAINT PK_Propietarios PRIMARY KEY (ID),
CONSTRAINT CK_Numero CHECK (Numero BETWEEN 1 AND 10),
)

CREATE TABLE Instituciones (
Nombre CHAR (30) NOT NULL,
Ciudad VARCHAR (40) NOT NULL,

CONSTRAINT PK_Instituciones PRIMARY KEY (Nombre),
)

CREATE TABLE Trabajadores (
ID SMALLINT NOT NULL,
Nombre VARCHAR (25) NOT NULL,
Apellidos VARCHAR (40) NOT NULL,
Direccion VARCHAR (80) NULL,
Categoria TINYINT NULL,
NombreCurro CHAR (30) NOT NULL,

CONSTRAINT PK_Trabajadores PRIMARY KEY (ID),
CONSTRAINT FK_Trabajadores_Institucion FOREIGN KEY (NombreCurro) REFERENCES Instituciones (Nombre) ON DELETE NO ACTION ON UPDATE CASCADE, 
CONSTRAINT CK_Categoria CHECK(Categoria BETWEEN 1 AND 4),
)

CREATE TABLE Ecologistas (
Nombre CHAR (40) NOT NULL,
Telefono CHAR (9) NULL,

CONSTRAINT PK_Ecologistas PRIMARY KEY (Nombre),
CONSTRAINT CK_Telefono CHECK (Telefono LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
)

CREATE TABLE Actos (
Nombre CHAR (30) NOT NULL,
Lugar VARCHAR (60) NULL,
Momento DATE NULL,
NombreEcologista CHAR (40) NOT NULL,

CONSTRAINT PK_Actos PRIMARY KEY (Nombre),
CONSTRAINT FK_Actos_Ecologistas FOREIGN KEY (NombreEcologista) REFERENCES Ecologistas (Nombre) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE Espias (
NombreClave CHAR (45) NOT NULL,
Nombre VARCHAR (25) NOT NULL,
Apellidos VARCHAR (45) NOT NULL,

CONSTRAINT PK_Espias PRIMARY KEY (NombreClave),
)

CREATE TABLE PuntosDebiles (
ID SMALLINT NOT NULL,
Nombre VARCHAR (40) NOT NULL,

CONSTRAINT PK_PuntosDebiles PRIMARY KEY (ID),
)

CREATE TABLE Parcelas_Limites (
IDParcela SMALLINT NOT NULL,
IDLimite SMALLINT NOT NULL,

CONSTRAINT PK_Parcelas_Limites PRIMARY KEY (IDParcela, IDLimite),
CONSTRAINT FK_ParcelasLimites_Parcelas FOREIGN KEY (IDParcela) REFERENCES Parcelas (ID) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_ParcelasLimites_Limites FOREIGN KEY (IDLimite) REFERENCES Limites (ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE Parcelas_Instituciones (
IDParcela SMALLINT NOT NULL,
NombreInstitucion CHAR (30) NOT NULL,

CONSTRAINT PK_Parcelas_Instituciones PRIMARY KEY (IDParcela, NombreInstitucion),
CONSTRAINT FK_ParcelasInstituciones_Parcelas FOREIGN KEY (IDParcela) REFERENCES Parcelas (ID) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_ParcelasInstituciones_Institucion FOREIGN KEY (NombreInstitucion) REFERENCES Instituciones (Nombre) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE Parcelas_Propietarios (
IDParcela SMALLINT NOT NULL,
IDPropietario SMALLINT NOT NULL,

CONSTRAINT PK_Parcelas_Propietarios PRIMARY KEY (IDParcela, IDPropietario),
CONSTRAINT FK_ParcelasPropietarios_Parcelas FOREIGN KEY (IDParcela) REFERENCES Parcelas (ID) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_ParcelasPropietarios_Propietarios FOREIGN KEY (IDPropietario) REFERENCES Propietarios (ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE Parcelas_Ecologistas (
IDParcela SMALLINT NOT NULL,
NombreEcologista CHAR (40) NOT NULL,

CONSTRAINT PK_Parcelas_Ecologistas PRIMARY KEY (IDParcela, NombreEcologista),
CONSTRAINT FK_ParcelasEcologistas_Parcelas FOREIGN KEY (IDParcela) REFERENCES Parcelas (ID) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_ParcelasEcologistas_Ecologista FOREIGN KEY (NombreEcologista) REFERENCES Ecologistas (Nombre) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE Debiles_Trabajadores (
IDPuntoDebil SMALLINT NOT NULL,
IDTrabajador SMALLINT NOT NULL,

CONSTRAINT PK_Debiles_Trabajadores PRIMARY KEY (IDPuntoDebil, IDTrabajador),
CONSTRAINT FK_DebilesTrabajadores_Debiles FOREIGN KEY (IDPuntoDebil) REFERENCES PuntosDebiles(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_DebilesTrabajadores_Trabajadores FOREIGN KEY (IDTrabajador) REFERENCES Trabajadores(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE Actos_Espias (
NombreActo CHAR (30) NOT NULL,
NombreClaveEspia CHAR (45) NOT NULL,

CONSTRAINT PK_Actos_Espias PRIMARY KEY (NombreActo, NombreClaveEspia),
CONSTRAINT FK_ActosEspias_Actos FOREIGN KEY (NombreActo) REFERENCES Actos(Nombre) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_ActosEspias_Espias FOREIGN KEY (NombreClaveEspia) REFERENCES Espias(NombreClave) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE Actos_Trabajadores (
NombreActo CHAR (30) NOT NULL,
IDTrabajador SMALLINT NOT NULL,
ISActuan BIT NOT NULL,

CONSTRAINT PK_Actos_Trabajadores PRIMARY KEY (NombreActo, IDTrabajador),
CONSTRAINT FK_ActosTrabajadores_Actos FOREIGN KEY (NombreActo) REFERENCES Actos(Nombre) ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT FK_ActosTrabajadores_Trabajadores FOREIGN KEY (IDTrabajador) REFERENCES Trabajadores(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
)